name: Automated Email Reminder

on:
  # Schedule the workflow to run every hour
  schedule:
    - cron: "0 16-23 * * *"  # 16:00 - 23:00 UTC maps to 0:00 - 7:00 SGT
    - cron: "0 0-15 * * *"  # 0:00 - 15:00 UTC maps to 8:00 - 23:00 SGT
jobs:
  run-email-reminder:
    runs-on: ubuntu-22.04  # Use the Ubuntu-22.04 
    env:
      TZ: "Asia/Singapore" # Set timezone to Singapore (Linux)
    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Fetch your repository's code

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: 3.x  # Specify Python version
      
    - name: Run the script
      env:  # Pass secrets as environment variables
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        EVENT_FILE: ${{ secrets.EVENT_FILE }}
      run: python main.py  # Execute your Python script

    - name: Commit changes to events.json # Commit back the changes made to events.json
    # Compare changes in the staging area to the last commit (--cached) without outputting any code, 
    # returning only an exit code (--quiet)
    # If no changes made to events.json, no commits will occur
    # If changes were made i.e exit code 1, next command after || operator will be executed, commit will occur
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
        git add events.json status.log
        git diff --cached --quiet || git commit -m "Update events.json and status.log"
        git push origin main
    
# Note: Enable read write permission under Settings > Actions > General > Workflow Permissions